_includes/compat-table.html, getting-started/react360.md, getting-started/reactvr.md
Updating some Oculus/FB related info
=> Update Oculus/FB info

_includes/compat-table.html
=> add update compat table

_includes/compat-table.html
Update the compat table for Magic Leap Helio.
=> Update compat table for ML Helio.

getting-started/babylon.md
getting started using babylon.js
=> Babylon.js update

getting-started/threejs.md
=> initial threejs example

getting-started/playcanvas.md
Adds basic PlayCanvas example of Immersive VR session.
=> Add PlayCanvas example

_includes/compat-table.html
This adds empty rows for dom-overlays, hit-test and layers
=> Add more modules to table

_includes/compat-table.html
=> Update compat-table.html for Samsung Internet

README.md, _includes/compat-table.html
+ fix one minor typo in readme
@AdaRoseCannon , @toji  - please take a look.
=> Add sections for Anchors and Depth Sensing

_includes/compat-table.html
=> replaced spec link with /TR/ ones

getting-started/aframe.md, getting-started/p5xr.md, getting-started/sumerian.md
Made some changes to improve A-Frame's description, filled in the Sumerian tab with instructions on how to make a basic scene and deploy it, added p5.xr tab with my own Hello World example.
=> Updated A-Frame, filled in Sumerian, added p5.xr

getting-started/react360.md
Removes react 360, thanks for the heads up Rik.
=> Remove React 360

_includes/compat-table.html
See https://chromestatus.com/feature/5742647199137792 and https://chromestatus.com/feature/5704707957850112
=> Update Chrome for Depth Sensing and Lighting Estimation

_includes/compat-table.html
I don't think Servo is being actively maintained at the moment. 
Is it okay to remove it?
=> Remove Servo for Hololens

_includes/compat-table.html
- Remove "not supported" from table (so that no green cell is rendered)
- Add MDN page for Hand Input
- Add spec and and MDN page for Depth Sensing
- Remove extraneous "15.2"
=> Update compat table

_includes/compat-table.html
Update compat table to include Edge
=> Update compat table to include Edge

_includes/compat-table.html
Microsoft Edge was in the Oculus Browser cell
=> Fix for the Additional Details raw

_includes/compat-table.html
Wolvic is a new browser based on FirefoxReality for AOSP devices.
=> Adding Wolvic to the compat table

_includes/compat-table.html
Adds the Immersive Web Emulator to the Compat Table
=> Update Immersive Web Emulator on the compat-table.html

_includes/compat-table.html
According to https://twitter.com/rcabanier/status/1617543719992836097 and personal testing
=> chore: Add Hit Test compatibility for Meta Quest Browser

_includes/compat-table.html
Based on the info in their Chinese WebXR docs https://developer-cn.pico-interactive.com/document/web/development-platform/
=> Update Pico support for WebXR AR Module and Layers

_includes/compat-table.html, main.css
This mainly adds some styling tweaks to the table to help add some visual balance/clarity between the table elements, as before it felt a bit barebones. It also adjusts a few instances of capitalization for consistency with their brand name. Screenshots below:
Before:
After:
=> Update compatability table to make it more readable

_includes/compat-table.html
This readds info for Servo's WebXR support. It also fixes a small typo I noticed
=> Readd Servo support info

_includes/compat-table.html
Wolvic can be used with Chromium as backend. Some versions of the browser were already released. By using this web engine Wolvic gained support of WebXR AR module and WebXR hand input so the table should be updated.
=> Updated table with Wolvic Chromium features
